server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 1234
  application:
    name: user-server
mybatis:
  type-aliases-package: cn.gaomengjie.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka